on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - uses: actions/checkout@v1
      - run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          ./pre-commit
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - if: success()
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v1
      - run: go test -v -covermode=count
